# Data cleaning using pandas

In this notebook, you'll see how clean structured data using `pandas`. We are aware that you have already done an extensive review of pandas, and are now experts in data manipulation, so we'll keep it short.

We are going to use a dataset about New York City Squirrels taken from [NYC Open Data](https://opendata.cityofnewyork.us/) which is a great resource for data sets.
This dataset is quite small and this notebook will just be an overview of different stuff to look out for when cleaning data.

In [5]:
import pandas as pd
import numpy as np

In [19]:
filename = "/Users/mustafagul/Desktop/LGG-Thomas4/02-TheHill/datasets/data.csv"
df = pd.read_csv(filename)
df.head(10)

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,NaN,Gray,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9702676472613 40.7762126854894)
5,-73.968361,40.772591,11H-AM-1010-03,11H,AM,10102018,3,Adult,Cinnamon,White,...,False,False,False,False,True,False,True,False,NaN,POINT (-73.9683613516225 40.7725908847499)
6,-73.954120,40.793181,36H-AM-1010-02,36H,AM,10102018,2,Adult,Gray,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9541201789795 40.7931811701082)
7,-73.958269,40.791737,33F-AM-1008-02,33F,AM,10082018,2,Adult,Gray,NaN,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9582694312289 40.7917367820255)
8,-73.967429,40.782972,21C-PM-1006-01,21C,PM,10062018,1,Adult,Gray,NaN,...,False,False,False,True,True,False,False,False,NaN,POINT (-73.9674285955293 40.7829723919744)
9,-73.972250,40.774288,11D-AM-1010-03,11D,AM,10102018,3,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9722500196844 40.7742879599026)

## Things to check

### Missing values

There are different ways that a value can be missing. It can be just an empty string (`""`), or `NaN` (Not a Number).
`np.nan`, `None` and `NaT` (for `datetime64` types) are standard missing value for Pandas.

You can either delete the rows/attribute if there are too many missing, or replace them. I can't give you a certain threshold to delete or replace, it really depends on the variable, on the context, and what you are going to do with the data later on.
In the same vein, there are many different ways to replace a value, and it will depend on the type of data you have. [[More info here]](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html)

Pandas provides `isnull()`, `isna()` functions to detect missing values. Both of them do the same thing.

In [12]:
print("There are {} rows of data".format(len(df)))

There are 3023 rows of data

We see that we have 3023 rows of data. Looking at the number of NaN values per column, one can confidently say that columns where we have > 1000 missing values are not worth keeping. The case can be made that, for certain scenarios, the columns `Highlight Fur Color` should be kept too, but here we are going to drop it because the column `Combination of Primary and Highlight Color` combines both.

This notebook is going to feature small code blocks that you'll have to complete.

The first task is to count how many nan values there are per attribute. Hint: use `df.isnull()`

In [57]:
# Check how many rows of each attribute are NaN
df.isna().sum()

X                                               0
Y                                               0
Unique Squirrel ID                              0
Hectare                                         0
Shift                                           0
Date                                            0
Hectare Squirrel Number                         0
Age                                           121
Primary Fur Color                              55
Combination of Primary and Highlight Color      0
Location                                       64
Above Ground Sighter Measurement              114
Running                                         0
Chasing                                         0
Climbing                                        0
Eating                                          0
Foraging                                        0
Kuks                                            0
Quaas                                           0
Moans                                           0
Tail flags                                      0
Tail twitches                                   0
Approaches                                      0
Indifferent                                     0
Runs from                                       0
Lat/Long                                        0
dtype: int64

Now that we've identified all the columns that have NaN values, we would like to drop those with more than 1000 NaN values.

Can you do that? Hint: `df.drop()`
  
Moreover, can you print the columns that were dropped, along with the number of missing values that they had?

In [45]:
# Drop the columns that have more than 1000 missing values
# Specific Location Other Interactions Color notes Highlight Fur Color
   
# Print the columns that were dropped
print(df)

              X          Y Unique Squirrel ID Hectare Shift      Date  \
0    -73.956134  40.794082     37F-PM-1014-03     37F    PM  10142018
1    -73.968857  40.783783     21B-AM-1019-04     21B    AM  10192018
2    -73.974281  40.775534     11B-PM-1014-08     11B    PM  10142018
3    -73.959641  40.790313     32E-PM-1017-14     32E    PM  10172018
4    -73.970268  40.776213     13E-AM-1017-05     13E    AM  10172018
...         ...        ...                ...     ...   ...       ...
3018 -73.963943  40.790868     30B-AM-1007-04     30B    AM  10072018
3019 -73.970402  40.782560     19A-PM-1013-05     19A    PM  10132018
3020 -73.966587  40.783678     22D-PM-1012-07     22D    PM  10122018
3021 -73.963994  40.789915     29B-PM-1010-02     29B    PM  10102018
3022 -73.975479  40.769640      5E-PM-1012-01     05E    PM  10122018

      Hectare Squirrel Number    Age Primary Fur Color  \
0                           3    NaN               NaN
1                           4    NaN               NaN
2                           8    NaN              Gray
3                          14  Adult              Gray
4                           5  Adult              Gray
...                       ...    ...               ...
3018                        4  Adult              Gray
3019                        5  Adult              Gray
3020                        7  Adult              Gray
3021                        2    NaN              Gray
3022                        1  Adult          Cinnamon

     Combination of Primary and Highlight Color  ... Foraging   Kuks  Quaas  \
0                                             +  ...    False  False  False
1                                             +  ...    False  False  False
2                                         Gray+  ...    False  False  False
3                                         Gray+  ...     True  False  False
4                                 Gray+Cinnamon  ...     True  False  False
...                                         ...  ...      ...    ...    ...
3018                                      Gray+  ...     True  False  False
3019                                 Gray+White  ...     True  False  False
3020                Gray+Black, Cinnamon, White  ...     True  False  False
3021                       Gray+Cinnamon, White  ...    False  False  False
3022                       Cinnamon+Gray, White  ...     True  False  False

      Moans  Tail flags  Tail twitches  Approaches  Indifferent  Runs from  \
0     False       False          False       False        False      False
1     False       False          False       False        False      False
2     False       False          False       False        False      False
3     False       False          False       False        False       True
4     False       False          False       False        False      False
...     ...         ...            ...         ...          ...        ...
3018  False       False          False       False        False       True
3019  False       False          False       False         True      False
3020  False       False          False       False         True      False
3021  False       False          False       False         True      False
3022  False       False          False        True        False      False

                                        Lat/Long
0     POINT (-73.9561344937861 40.7940823884086)
1     POINT (-73.9688574691102 40.7837825208444)
2     POINT (-73.97428114848522 40.775533619083)
3     POINT (-73.9596413903948 40.7903128889029)
4     POINT (-73.9702676472613 40.7762126854894)
...                                          ...
3018  POINT (-73.9639431360458 40.7908677445466)
3019  POINT (-73.9704015859639 40.7825600069973)
3020  POINT (-73.9665871993517 40.7836775064883)
3021  POINT (-73.9639941227864 40.7899152327912)
3022  POINT (-73.9754794191553 40.7696404489025)

[3023 rows x 26 columns]

### Attribute type

Sometimes, an attribute does not have the correct type, e.g. integers are labeled as floats. So it is useful to check if it needs to be changed or not.


Please print the dtypes of every attribute.

In [62]:
# Print the dtype of every attribute
df.dtypes

X                                             float64
Y                                             float64
Unique Squirrel ID                             object
Hectare                                        object
Shift                                          object
Date                                            int64
Hectare Squirrel Number                         int64
Age                                            object
Primary Fur Color                              object
Combination of Primary and Highlight Color     object
Location                                       object
Above Ground Sighter Measurement               object
Running                                          bool
Chasing                                          bool
Climbing                                         bool
Eating                                           bool
Foraging                                         bool
Kuks                                             bool
Quaas                                            bool
Moans                                            bool
Tail flags                                       bool
Tail twitches                                    bool
Approaches                                       bool
Indifferent                                      bool
Runs from                                        bool
Lat/Long                                       object
dtype: object

For example, for `Hectare`, one could think that the variable is just the size of the plot of land. However, it seems it is just an identifier for which plot of land it is. One would have to see the documentation to know for sure. In this case, the `object` dtype is appropriate.

In [146]:
# Print unique values of the "Hectare" attribute
df['Hectare'].unique()

array(['37F', '21B', '11B', '32E', '13E', '11H', '36H', '33F', '21C',
       '11D', '20B', '22F', '36I', '05C', '07H', '16C', '14E', '32A',
       '17F', '16I', '12I', '32F', '25A', '15E', '39G', '29I', '07E',
       '17C', '10A', '28A', '12B', '18A', '33H', '29C', '38C', '31H',
       '08H', '34F', '13H', '35C', '17E', '02B', '19D', '40B', '03E',
       '39C', '06G', '14F', '06I', '15F', '08B', '03A', '05E', '05F',
       '16E', '13F', '29H', '23C', '33C', '38G', '16G', '35A', '28C',
       '32D', '22A', '19C', '15G', '10F', '42E', '22B', '05A', '32H',
       '42C', '41D', '21G', '07F', '38F', '41B', '36A', '31A', '42G',
       '37D', '37E', '24B', '07G', '15I', '19B', '13D', '35B', '40D',
       '38B', '40I', '07B', '40A', '03B', '21D', '10B', '41A', '02F',
       '26A', '35E', '11G', '07A', '03D', '35D', '18G', '06F', '09F',
       '38E', '33G', '32G', '04D', '06H', '15D', '39H', '20F', '09G',
       '05D', '23F', '39A', '13A', '10G', '13C', '32C', '31D', '18C',
       '40E', '04G', '12F', '17H', '03G', '15H', '14G', '42H', '38A',
       '22C', '36F', '05I', '16D', '06D', '12E', '14D', '22D', '08A',
       '02D', '12C', '08F', '02H', '32B', '04E', '14A', '09B', '08C',
       '06B', '39B', '03C', '38D', '10C', '26I', '01B', '09A', '37H',
       '06A', '32I', '02E', '04B', '31F', '23D', '30B', '04F', '33I',
       '37C', '33B', '37I', '37G', '20A', '15A', '16F', '01G', '37B',
       '03I', '12G', '10I', '19H', '34I', '12A', '19F', '20C', '36E',
       '28D', '21E', '39F', '27A', '18D', '27I', '14I', '01H', '30E',
       '16A', '11E', '22I', '41C', '29B', '15B', '18I', '12D', '11F',
       '34D', '20D', '21F', '33D', '08E', '33E', '31G', '02C', '04I',
       '40C', '10H', '30D', '36C', '11I', '01D', '22G', '40G', '01C',
       '07I', '14H', '08I', '13B', '34H', '04A', '42F', '41I', '12H',
       '09C', '36B', '31E', '29D', '42D', '19G', '13I', '24A', '36D',
       '42B', '41E', '18F', '16H', '09D', '07D', '08G', '04C', '23E',
       '30A', '15C', '16B', '11A', '36G', '14C', '21H', '05G', '03F',
       '42I', '14B', '01A', '09I', '18H', '26B', '28I', '01F', '31I',
       '17A', '03H', '02A', '30I', '09E', '39D', '34E', '17D', '21A',
       '13G', '35F', '38I', '09H', '30C', '19E', '08D', '04H', '23B',
       '20G', '17G', '35G', '02I', '10D', '17I', '42A', '34B', '17B',
       '11C', '33A', '31B', '25I', '37A', '01E', '22H', '34A', '19A',
       '06C', '07C', '05B', '23A', '02G', '35H', '06E', '41G', '40H',
       '39I', '23I', '31C', '29A', '22E', '41F', '28B', '35I', '24I',
       '23H', '34C', '39E', '01I', '18E', '27B', '34G', '05H', '40F',
       '30H', '10E', '25B', '20E', '38H', '30F'], dtype=object)

### Attribute values

Carefully check each attribute to see if the unique values are coherent and make sense.
Moreover, check that minimum and maximum values make sense. (e.g. age of a person that is negative)

Hint: use your previously acquired knowledge of extracting unique values.
Be careful to limit the attributes that you print by the number of unique values they have, as there are fields that have all their values that are unique, and we don't want a kilometer long list of each value.

In [144]:
# Print the number of unique values of each column, only printing those that have less than 100 unique values
columns_unique = [i for i in df.columns if df[i].nunique() < 100]

df[columns_unique].nunique()

Shift                                          2
Date                                          11
Hectare Squirrel Number                       23
Age                                            3
Primary Fur Color                              3
Combination of Primary and Highlight Color    22
Location                                       2
Above Ground Sighter Measurement              41
Running                                        2
Chasing                                        2
Climbing                                       2
Eating                                         2
Foraging                                       2
Kuks                                           2
Quaas                                          2
Moans                                          2
Tail flags                                     2
Tail twitches                                  2
Approaches                                     2
Indifferent                                    2
Runs from                                      2
dtype: int64

In [147]:
df.describe(include="all").T  # Transpose the data frame so that it fits in a cell

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
X,3023.0,NaN,NaN,NaN,-73.967184,0.007726,-73.981159,-73.973102,-73.968594,-73.960189,-73.949722
Y,3023.0,NaN,NaN,NaN,40.780853,0.010285,40.764911,40.771676,40.778166,40.791219,40.800119
Unique Squirrel ID,3023,3018,7D-PM-1010-01,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hectare,3023,339,14D,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shift,3023,2,PM,1676,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,3023.0,NaN,NaN,NaN,10119487.401257,42466.714959,10062018.0,10082018.0,10122018.0,10142018.0,10202018.0
Hectare Squirrel Number,3023.0,NaN,NaN,NaN,4.123718,3.096492,1.0,2.0,3.0,6.0,23.0
Age,2902,3,Adult,2568,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Primary Fur Color,2968,3,Gray,2473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Combination of Primary and Highlight Color,3023,22,Gray+,895,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location,2959,2,Ground Plane,2116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Above Ground Sighter Measurement,2909,41,FALSE,2116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Running,3023,2,False,2293,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chasing,3023,2,False,2744,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Climbing,3023,2,False,2365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Eating,3023,2,False,2263,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Foraging,3023,2,False,1588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kuks,3023,2,False,2921,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quaas,3023,2,False,2973,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Moans,3023,2,False,3020,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tail flags,3023,2,False,2868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tail twitches,3023,2,False,2589,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Approaches,3023,2,False,2845,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indifferent,3023,2,False,1569,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Runs from,3023,2,False,2345,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lat/Long,3023,3023,POINT (-73.9561344937861 40.7940823884086),1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Does something stand out to you?**

In the column `Combination of Primary and Highlight Color` for example, we have a value that is only `"+"`.
Again, there are multiple ways to deal with this. When you can't figure out what the value means (like in this case), you can drop it. Sometimes, when you are able to figure out which one is meant, you can replace it with the correct value. This is where the domain knowledge come into play, knowing which variable can be replaced with what, and what it could mean.

Another example, from another dataset containing vehicle types where the vehicle type was manually encoded.
You see how `"Tow truck"` appears in many different forms.
The right approach is to consolidate all of the different values of tow truck into a single one.

In [90]:
trucks = ["Pick-up Truck", "Tractor Truck Diesel", "Box Truck", "Tractor Truck Gasoline", "Tow Truck / Wrecker", "Beverage Truck", "truck", "Armored Truck", "TRUCK", "Truck", "Tow Truck", "FIRE TRUCK", "PICK-UP TRUCK", "BOX TRUCK", "Fire Truck", "box truck", "TRUCK FLAT", "FIRTRUCK", "TRUCK VAN", "FIRETRUCK", "FDNY TRUCK", "dump truck", "Fire truck", "UPS TRUCK", "fire truck", "FOOD TRUCK", "MAIL TRUCK", "USPS TRUCK", "tow truck", "TOW TRUCK", "Tow truck"]
[truck for truck in trucks if "tow" in truck.lower()]

['Tow Truck / Wrecker', 'Tow Truck', 'tow truck', 'TOW TRUCK', 'Tow truck']

### Duplicates

Search for duplicates and remove them

In [148]:
# There are no duplicates
df.duplicated().any()

False

If there had been, call `df.drop_duplicates(inplace=True)` to remove them.

Again, this is just a short introduction to data cleaning of structured data, there are many more steps that one could optionally take.

## References and reading material

[Data cleaning challenge - Kaggle](https://www.kaggle.com/rtatman/data-cleaning-challenge-handling-missing-values)  
[Preparing data for a machine learning model - Dataquest](https://www.dataquest.io/blog/machine-learning-preparing-data/)  
[Preliminary data cleaning - Kaggle](https://www.kaggle.com/quannguyen135/preliminary-data-cleaning-with-python)  
[Pandas data cleaning cheatsheet - Elite Data Science](https://elitedatascience.com/python-cheat-sheet)